# Generated by Django 3.2.4 on 2021-06-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='product',
            name='graphics',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
