# Generated by Django 3.2.4 on 2021-06-21 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('CPU', 'CPU'), ('GPU', 'GPU'), ('Mobo', 'Mobo'), ('Memory', 'Memory'), ('Case', 'Case'), ('PSU', 'PSU'), ('CaseAcc', 'CaseAcc'), ('Headset', 'Headset'), ('Keyboard', 'Keyboard'), ('Monitor', 'Monitor'), ('Mouse', 'Mouse')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('cores', models.FloatField()),
                ('clockspeed', models.FloatField()),
                ('graphics', models.CharField(max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.cpu'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.cpu'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
