# Generated by Django 3.2.4 on 2021-06-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_auto_20210622_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAcc',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('rpm', models.FloatField()),
                ('size', models.FloatField()),
            ],
            bases=('items.product',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('chipset', models.CharField(max_length=200, null=True)),
                ('vram', models.FloatField()),
                ('clockspeed', models.FloatField()),
            ],
            bases=('items.product',),
        ),
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('wireless', models.BooleanField()),
            ],
            bases=('items.product',),
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('switchtype', models.CharField(max_length=200, null=True)),
                ('switch', models.CharField(max_length=200, null=True)),
            ],
            bases=('items.product',),
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('memorytype', models.CharField(max_length=200, null=True)),
                ('speed', models.FloatField()),
                ('capacity', models.FloatField()),
            ],
            bases=('items.product',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('resolution', models.CharField(max_length=200, null=True)),
                ('refreshrate', models.FloatField()),
            ],
            bases=('items.product',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('socket', models.CharField(max_length=200, null=True)),
                ('formfactor', models.CharField(max_length=200, null=True)),
            ],
            bases=('items.product',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('dpi', models.FloatField()),
                ('wireless', models.BooleanField()),
            ],
            bases=('items.product',),
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('capacity', models.FloatField()),
            ],
            bases=('items.product',),
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('storagetype', models.CharField(max_length=200, null=True)),
                ('capacity', models.FloatField()),
            ],
            bases=('items.product',),
        ),
    ]
