# Generated by Django 3.2.4 on 2021-06-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_caseacc_gpu_headset_keyboard_memory_monitor_motherboard_mouse_psu_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
