# Generated by Django 3.2.4 on 2021-06-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_auto_20210622_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('casetype', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
            ],
            bases=('items.product',),
        ),
    ]
