# Generated by Django 3.2.4 on 2021-06-22 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUCooler',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='items.product')),
                ('coolertype', models.CharField(max_length=200, null=True)),
                ('rpm', models.FloatField()),
            ],
            bases=('items.product',),
        ),
    ]
