# Generated by Django 3.0.14 on 2021-06-23 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_auto_20210623_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='state',
            new_name='country',
        ),
    ]
